from librarian.extractors import txt   # noqa: F401  (регистрация в EXTRACTORS)
from librarian.extractors import md    # noqa: F401  (регистрация в EXTRACTORS)
from librarian.extractors import fb2   # noqa: F401  (регистрация в EXTRACTORS)
from librarian.extractors import epub  # noqa: F401  (регистрация в EXTRACTORS)
from librarian.extractors import docx  # noqa: F401  (регистрация в EXTRACTORS)
